name: Deploy to Namecheap
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Namecheap via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.W1_HOST }}
          port: ${{ secrets.W1_PORT }}
          username: ${{ secrets.W1_USERNAME }}
          password: ${{ secrets.W1_PASSWORD }} # Or use key: ${{ secrets.W1_SSH_KEY }}
          script: |
            cd ~/public_html
            git pull origin main
            # Additional commands (e.g., for PHP apps)
            # composer install
            # bin/console cache:clear
            echo "Deployment successful!"
