name: Deploy to Namecheap via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}  # Ensure this matches your secret
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/  # Adjust to your project folder
          server-dir: /public_html/
          protocol: ftp
          log-level: verbose  # For debugging
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            .gitignore
