name: Deploy to Namecheap via FTP
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.FTP_HOST }} # e.g., server123.web-hosting.com
          username: ${{ secrets.FTP_USERNAME }} # e.g., user123 or ftpuser@yourdomain.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21 # Specify the port here (21 for FTP, 22 for SFTP, or 21098 if using Namecheap’s SSH-based SFTP)
          server-dir: /public_html/
          local-dir: ./
